### PR TITLE
Translation into Russian, DeepLinking

### PR DESCRIPTION
**Pull request by aksenovaa**

### CODE REVIEW

**Comment by aksenovaa** [comment]
The translation of this document is finished, I look forward to comments if any.

**Comment by brotkrueml** [comment]
@aksenovaa One tip for the future: Convert the PR to a draft if you are working on it, so it is clear it is not ready for now for a review. After everything is complete, mark it as ready.

**Comment by aksenovaa** [comment]
> @aksenovaa One tip for the future: Convert the PR to a draft if you are working on it, so it is clear it is not ready for now for a review. After everything is complete, mark it as ready.
I'll keep in mind, the process of transferring documentation is not described step by step anywhere. So that's how it works.

**Comment by aksenovaa** [comment]
It's finished.

**Review by brotkrueml — APPROVED** [review]

**Comment by brotkrueml** [comment]
@aksenovaa Sorry for the late response.

**Pull request merged**
