### PR TITLE
Appearance Screenshot under Behaviour section.

### PR DESCRIPTION
**Pull request by heidi37**
The "Appearance" screen shot was showing under the "Appearance" and "Behaviour"  sections. I removed it under "Behaviour" as it was a picture of the "Appearance" tab. If there is a screenshot available with the "Behaviour" that would be helpful to add.

### CODE REVIEW

**Comment by linawolf** [comment]
I would close your PR here as I would like to create a new PR which is fixing the screenshots right away. Thanks for catching this.

**Comment by heidi37** [comment]
Hi Lina, I am kinda new to this. 😄  I see that you closed my PR and made it an issue in your repo. On my side it isn't a PR any more. So in my repo should I delete the branch or I can also delete the fork it says. Thank you for your patience with a newbie. If I can close the PR on my side, please let me know how. Thank you!

**Comment by linawolf** [comment]
Yes no worries, you can delete your branch. We are in the middle of automating the screenshots for this tutorial so I will include this issue and take care of it

**Comment by heidi37** [comment]
Thank you Lina! I deleted my branch and I received the "pull request closed" message.

**Pull request closed without merging**
